// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialChef.Domain.Relational;

namespace SocialChef.Domain.Relational.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20200516171548_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SocialChef.Domain.Relational.ChefDao", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("Chefs");
                });

            modelBuilder.Entity("SocialChef.Domain.Relational.ChefRecipe", b =>
                {
                    b.Property<Guid>("ChefID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipeID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ChefID", "RecipeID");

                    b.ToTable("ChefRecipes");
                });

            modelBuilder.Entity("SocialChef.Domain.Relational.ChefRecipe", b =>
                {
                    b.HasOne("SocialChef.Domain.Relational.ChefDao", "Chef")
                        .WithMany("Recipes")
                        .HasForeignKey("ChefID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
