// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialChef.Domain.Relational;

namespace SocialChef.Domain.Relational.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    partial class SqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SocialChef.Domain.Relational.ChefDao", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("Chefs");
                });

            modelBuilder.Entity("SocialChef.Domain.Relational.RecipeSummaryDao", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChefDaoID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StepCount")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ChefDaoID");

                    b.ToTable("RecipeSummaries");
                });

            modelBuilder.Entity("SocialChef.Domain.Relational.RecipeSummaryDao", b =>
                {
                    b.HasOne("SocialChef.Domain.Relational.ChefDao", null)
                        .WithMany("Recipes")
                        .HasForeignKey("ChefDaoID");
                });
#pragma warning restore 612, 618
        }
    }
}
